version: '3.5'

services:
  ldap:
    container_name: ldap
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
    volumes:
      - ./ldap/database:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    networks:
      - app-network
    restart: unless-stopped
  backend_api:
    container_name: backend_api
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - ldap
    environment:
      API_PORT: 3001
      LDAP_URL: "ldap://ldap"
      SECRET: "StringParaCriptografarSenhas"
      LDAP_USUARIO: "cn=admin,dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_BASEDN: "dc=example,dc=com"
      LDAP_BASEDN_USUARIOS: "ou=people,dc=example,dc=com"
      LDAP_BASEDN_GRUPOS: "ou=groups,dc=example,dc=com"
    ports:
      - 3001:3001
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
